language: node_js

services:
  - mongodb

before_install:
  - sudo apt-get update
  - sudo apt-get install php5-cli php5-curl libgeoip-dev
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.10.deb
  - dpkg -i elasticsearch-0.90.10.deb
  - sudo /etc/init.d/elasticsearch start
  - cp config/elasticsearch.cfg.sample config/elasticsearch.cfg
  - cp config/mongo.cfg.sample config/mongo.cfg
  - cp config/server.json.sample config/server.json

node_js:
  - "0.10"
  - "0.8"
  - "0.6"

script:
  - make test
