language: node_js

services:
  - elasticsearch
  - mongodb

before_install:
  - composer self-update
  - composer install --dev
  - sudo apt-get update
  - sudo apt-get install php5 libgeoip-dev
  - cp config/elasticsearch.cfg.sample config/elasticsearch.cfg
  - cp config/mongo.cfg.sample config/mongo.cfg
  - cp config/server.json.sample config/server.json

node_js:
  - "0.10"
  - "0.8"
  - "0.6"

script:
  - make test
